package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAdminIntegration;
import org.linlinjava.litemall.db.domain.LitemallAdminIntegrationExample;

public interface LitemallAdminIntegrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    long countByExample(LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int insert(LitemallAdminIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAdminIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    LitemallAdminIntegration selectOneByExample(LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    LitemallAdminIntegration selectOneByExampleSelective(@Param("example") LitemallAdminIntegrationExample example, @Param("selective") LitemallAdminIntegration.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    List<LitemallAdminIntegration> selectByExampleSelective(@Param("example") LitemallAdminIntegrationExample example, @Param("selective") LitemallAdminIntegration.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    List<LitemallAdminIntegration> selectByExample(LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    LitemallAdminIntegration selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAdminIntegration.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    LitemallAdminIntegration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAdminIntegration record, @Param("example") LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAdminIntegration record, @Param("example") LitemallAdminIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAdminIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAdminIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallAdminIntegration> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_admin_integration
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallAdminIntegration> list, @Param("selective") LitemallAdminIntegration.Column ... selective);
}