package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTypeRole;
import org.linlinjava.litemall.db.domain.LitemallTypeRoleExample;

public interface LitemallTypeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    long countByExample(LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int insert(LitemallTypeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTypeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    LitemallTypeRole selectOneByExample(LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    LitemallTypeRole selectOneByExampleSelective(@Param("example") LitemallTypeRoleExample example, @Param("selective") LitemallTypeRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    List<LitemallTypeRole> selectByExampleSelective(@Param("example") LitemallTypeRoleExample example, @Param("selective") LitemallTypeRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    List<LitemallTypeRole> selectByExample(LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    LitemallTypeRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTypeRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    LitemallTypeRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTypeRole record, @Param("example") LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTypeRole record, @Param("example") LitemallTypeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTypeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTypeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallTypeRole> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_type_role
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallTypeRole> list, @Param("selective") LitemallTypeRole.Column ... selective);
}