package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsDispatchHistory;
import org.linlinjava.litemall.db.domain.LitemallGoodsDispatchHistoryExample;

public interface LitemallGoodsDispatchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsDispatchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsDispatchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    LitemallGoodsDispatchHistory selectOneByExample(LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    LitemallGoodsDispatchHistory selectOneByExampleSelective(@Param("example") LitemallGoodsDispatchHistoryExample example, @Param("selective") LitemallGoodsDispatchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    List<LitemallGoodsDispatchHistory> selectByExampleSelective(@Param("example") LitemallGoodsDispatchHistoryExample example, @Param("selective") LitemallGoodsDispatchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    List<LitemallGoodsDispatchHistory> selectByExample(LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    LitemallGoodsDispatchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsDispatchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    LitemallGoodsDispatchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    LitemallGoodsDispatchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsDispatchHistory record, @Param("example") LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsDispatchHistory record, @Param("example") LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsDispatchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsDispatchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsDispatchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallGoodsDispatchHistory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_dispatch_history
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallGoodsDispatchHistory> list, @Param("selective") LitemallGoodsDispatchHistory.Column ... selective);
}