package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductAgent;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductAgentExample;

public interface LitemallGoodsProductAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsProductAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsProductAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    LitemallGoodsProductAgent selectOneByExample(LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    LitemallGoodsProductAgent selectOneByExampleSelective(@Param("example") LitemallGoodsProductAgentExample example, @Param("selective") LitemallGoodsProductAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductAgent> selectByExampleSelective(@Param("example") LitemallGoodsProductAgentExample example, @Param("selective") LitemallGoodsProductAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductAgent> selectByExample(LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    LitemallGoodsProductAgent selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsProductAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    LitemallGoodsProductAgent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    LitemallGoodsProductAgent selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsProductAgent record, @Param("example") LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsProductAgent record, @Param("example") LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsProductAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsProductAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsProductAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallGoodsProductAgent> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_agent
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallGoodsProductAgent> list, @Param("selective") LitemallGoodsProductAgent.Column ... selective);
}