package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsExtraInfo;
import org.linlinjava.litemall.db.domain.LitemallGoodsExtraInfoExample;

public interface LitemallGoodsExtraInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsExtraInfo selectOneByExample(LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsExtraInfo selectOneByExampleSelective(@Param("example") LitemallGoodsExtraInfoExample example, @Param("selective") LitemallGoodsExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    List<LitemallGoodsExtraInfo> selectByExampleSelective(@Param("example") LitemallGoodsExtraInfoExample example, @Param("selective") LitemallGoodsExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    List<LitemallGoodsExtraInfo> selectByExample(LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsExtraInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsExtraInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsExtraInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsExtraInfo record, @Param("example") LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsExtraInfo record, @Param("example") LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallGoodsExtraInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_extra_info
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallGoodsExtraInfo> list, @Param("selective") LitemallGoodsExtraInfo.Column ... selective);
}