package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductExtraInfo;
import org.linlinjava.litemall.db.domain.LitemallGoodsProductExtraInfoExample;

public interface LitemallGoodsProductExtraInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int insert(LitemallGoodsProductExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallGoodsProductExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsProductExtraInfo selectOneByExample(LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsProductExtraInfo selectOneByExampleSelective(@Param("example") LitemallGoodsProductExtraInfoExample example, @Param("selective") LitemallGoodsProductExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductExtraInfo> selectByExampleSelective(@Param("example") LitemallGoodsProductExtraInfoExample example, @Param("selective") LitemallGoodsProductExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    List<LitemallGoodsProductExtraInfo> selectByExample(LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsProductExtraInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallGoodsProductExtraInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsProductExtraInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    LitemallGoodsProductExtraInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallGoodsProductExtraInfo record, @Param("example") LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallGoodsProductExtraInfo record, @Param("example") LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallGoodsProductExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallGoodsProductExtraInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallGoodsProductExtraInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallGoodsProductExtraInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_goods_product_extra_info
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallGoodsProductExtraInfo> list, @Param("selective") LitemallGoodsProductExtraInfo.Column ... selective);
}