package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAccountHistory;
import org.linlinjava.litemall.db.domain.LitemallAccountHistoryExample;

public interface LitemallAccountHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    long countByExample(LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int insert(LitemallAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    LitemallAccountHistory selectOneByExample(LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    LitemallAccountHistory selectOneByExampleSelective(@Param("example") LitemallAccountHistoryExample example, @Param("selective") LitemallAccountHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    List<LitemallAccountHistory> selectByExampleSelective(@Param("example") LitemallAccountHistoryExample example, @Param("selective") LitemallAccountHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    List<LitemallAccountHistory> selectByExample(LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    LitemallAccountHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAccountHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    LitemallAccountHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    LitemallAccountHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAccountHistory record, @Param("example") LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAccountHistory record, @Param("example") LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAccountHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallAccountHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<LitemallAccountHistory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_history
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<LitemallAccountHistory> list, @Param("selective") LitemallAccountHistory.Column ... selective);
}